test: &test
  adapter: postgresql
  encoding: unicode
  database: ccs_test
  pool: 5
  user: ccs
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: ccs_development
  pool: 5
  user: ccs
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ccs_production
  pool: 5
  user: ccs
  host: localhost

cucumber:
  <<: *test
