development:
  adapter: postgresql
  encoding: unicode
  database: ccs_dev
  pool: 5
  username: postgres
  password: secret
  host: db

test: &test
  adapter: postgresql
  encoding: unicode
  database: ccs_test
  pool: 5
  username: postgres
  password: secret
  host: db

production:
  adapter: postgresql
  encoding: unicode
  database: ccs_production
  pool: 5
  user: ccs
  host: localhost

cucumber:
  <<: *test
