require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SesjasController do

  def mock_sesja(stubs={})
    @mock_sesja ||= mock_model(Sesja, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sesjas as @sesjas" do
      Sesja.stub(:all) { [mock_sesja] }
      get :index
      assigns(:sesjas).should eq([mock_sesja])
    end
  end

  describe "GET show" do
    it "assigns the requested sesja as @sesja" do
      Sesja.stub(:find).with("37") { mock_sesja }
      get :show, :id => "37"
      assigns(:sesja).should be(mock_sesja)
    end
  end

  describe "GET new" do
    it "assigns a new sesja as @sesja" do
      Sesja.stub(:new) { mock_sesja }
      get :new
      assigns(:sesja).should be(mock_sesja)
    end
  end

  describe "GET edit" do
    it "assigns the requested sesja as @sesja" do
      Sesja.stub(:find).with("37") { mock_sesja }
      get :edit, :id => "37"
      assigns(:sesja).should be(mock_sesja)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created sesja as @sesja" do
        Sesja.stub(:new).with({'these' => 'params'}) { mock_sesja(:save => true) }
        post :create, :sesja => {'these' => 'params'}
        assigns(:sesja).should be(mock_sesja)
      end

      it "redirects to the created sesja" do
        Sesja.stub(:new) { mock_sesja(:save => true) }
        post :create, :sesja => {}
        response.should redirect_to(sesja_url(mock_sesja))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sesja as @sesja" do
        Sesja.stub(:new).with({'these' => 'params'}) { mock_sesja(:save => false) }
        post :create, :sesja => {'these' => 'params'}
        assigns(:sesja).should be(mock_sesja)
      end

      it "re-renders the 'new' template" do
        Sesja.stub(:new) { mock_sesja(:save => false) }
        post :create, :sesja => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sesja" do
        Sesja.stub(:find).with("37") { mock_sesja }
        mock_sesja.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :sesja => {'these' => 'params'}
      end

      it "assigns the requested sesja as @sesja" do
        Sesja.stub(:find) { mock_sesja(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:sesja).should be(mock_sesja)
      end

      it "redirects to the sesja" do
        Sesja.stub(:find) { mock_sesja(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(sesja_url(mock_sesja))
      end
    end

    describe "with invalid params" do
      it "assigns the sesja as @sesja" do
        Sesja.stub(:find) { mock_sesja(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:sesja).should be(mock_sesja)
      end

      it "re-renders the 'edit' template" do
        Sesja.stub(:find) { mock_sesja(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sesja" do
      Sesja.stub(:find).with("37") { mock_sesja }
      mock_sesja.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sesjas list" do
      Sesja.stub(:find) { mock_sesja }
      delete :destroy, :id => "1"
      response.should redirect_to(sesjas_url)
    end
  end

end
