require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SponsorsController do

  def mock_sponsor(stubs={})
    @mock_sponsor ||= mock_model(Sponsor, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sponsors as @sponsors" do
      Sponsor.stub(:all) { [mock_sponsor] }
      get :index
      assigns(:sponsors).should eq([mock_sponsor])
    end
  end

  describe "GET show" do
    it "assigns the requested sponsor as @sponsor" do
      Sponsor.stub(:find).with("37") { mock_sponsor }
      get :show, :id => "37"
      assigns(:sponsor).should be(mock_sponsor)
    end
  end

  describe "GET new" do
    it "assigns a new sponsor as @sponsor" do
      Sponsor.stub(:new) { mock_sponsor }
      get :new
      assigns(:sponsor).should be(mock_sponsor)
    end
  end

  describe "GET edit" do
    it "assigns the requested sponsor as @sponsor" do
      Sponsor.stub(:find).with("37") { mock_sponsor }
      get :edit, :id => "37"
      assigns(:sponsor).should be(mock_sponsor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created sponsor as @sponsor" do
        Sponsor.stub(:new).with({'these' => 'params'}) { mock_sponsor(:save => true) }
        post :create, :sponsor => {'these' => 'params'}
        assigns(:sponsor).should be(mock_sponsor)
      end

      it "redirects to the created sponsor" do
        Sponsor.stub(:new) { mock_sponsor(:save => true) }
        post :create, :sponsor => {}
        response.should redirect_to(sponsor_url(mock_sponsor))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sponsor as @sponsor" do
        Sponsor.stub(:new).with({'these' => 'params'}) { mock_sponsor(:save => false) }
        post :create, :sponsor => {'these' => 'params'}
        assigns(:sponsor).should be(mock_sponsor)
      end

      it "re-renders the 'new' template" do
        Sponsor.stub(:new) { mock_sponsor(:save => false) }
        post :create, :sponsor => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sponsor" do
        Sponsor.stub(:find).with("37") { mock_sponsor }
        mock_sponsor.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :sponsor => {'these' => 'params'}
      end

      it "assigns the requested sponsor as @sponsor" do
        Sponsor.stub(:find) { mock_sponsor(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:sponsor).should be(mock_sponsor)
      end

      it "redirects to the sponsor" do
        Sponsor.stub(:find) { mock_sponsor(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(sponsor_url(mock_sponsor))
      end
    end

    describe "with invalid params" do
      it "assigns the sponsor as @sponsor" do
        Sponsor.stub(:find) { mock_sponsor(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:sponsor).should be(mock_sponsor)
      end

      it "re-renders the 'edit' template" do
        Sponsor.stub(:find) { mock_sponsor(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sponsor" do
      Sponsor.stub(:find).with("37") { mock_sponsor }
      mock_sponsor.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sponsors list" do
      Sponsor.stub(:find) { mock_sponsor }
      delete :destroy, :id => "1"
      response.should redirect_to(sponsors_url)
    end
  end

end
